# Site settings
title: Rommell's Boilerplate
tagline: Boilerplate code for hosting a static holding page on GitHub pages

url: "" # the base hostname & protocol for your site

# Used for theme in head.html, cannot be used in Stylus files
color-primary: "#263238"

# contact
author:
  name: Rommell Allen
  url: http://github.com/neoremz

twitter_username: neoremz
github_username:  neoremz
github_url: "https://github.com/NeoRemz/rommell.site"

# Others
markdown: redcarpet

# Exclude Stylus files, nodemodules, and gulpfile
exclude: [node_modules, gulpfile.js, styl, npm-debug.log, Gemfile, Gemfile.lock, LICENSE, README.md, package.json]
